name: Blacklist Email
description: Report an email to be added to the blacklist
title: "[Report]: [EMAIL]"
labels: ["blacklist"]
assignees:
  - sefinek24

body:
  - type: input
    id: email
    attributes:
      label: Email
      value: "test@example.com"
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: Title
      value: "Test 2"
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: Date
      value: "15.09.2024"
    validations:
      required: true

  - type: textarea
    id: content
    attributes:
      label: Content
      value: "test 123"
    validations:
      required: true
